{
 "title": "Syscall Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Number of failures",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "failed_syscalls_total" }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(failed_syscalls_total[10s])"
    }
   ]
  },
  {
   "title": "Total Execution Time of Failed Syscalls",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "failed_syscalls_latency_total" }
   ]
  },
  {
   "title": "Rate of Latencies",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(failed_syscalls_latency_total[10s])"
    }
   ]
  }
 ]
}